### ISSUE TITLE
This library is great, I integrated it in chatgpt app and everything works fine, thanks for the contribution

### ISSUE THREAD

**Issue by lencx** [liady/ChatGPT-pdf#15]
ref: https://github.com/lencx/ChatGPT/blob/main/src-tauri/src/assets/export.js

**Comment by liady** [comment]
Thank you! The app looks nice as well. 

One thing - Since your code is a direct copy-paste of mine - you can give a clearer credit to it in the Readme (for example "The share buttons code is copied directly from @liady extension: ... ").
Currently this extension appears only in the "related" part which is misleading.

Anyway good job on the app!

**Comment by lencx** [comment]
Thanks for the reminder, I have modified it in the readme.

<img width="908" alt="Screenshot 2022-12-12 at 16 27 25" src="https://user-images.githubusercontent.com/16164244/206997177-8a4f5b90-f2b2-4a97-8f1e-22cb14433d2b.png">
