### ISSUE TITLE
MSEDGE: Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by tradeshark** [liady/ChatGPT-pdf#41]
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Elements.fixLocation (content_script.js:200:17)
    at downloadThread (content_script.js:112:12)
    at downloadButton.onclick (content_script.js:89:5)

**Comment by remiville** [comment]
I had the same error (chrome 110.0.5481.104, chatGPT feb13 https://help.openai.com/en/articles/6825453-chatgpt-release-notes)

I ~ "fixed" it (I'm not familiar with JavaScript or browser plugin development) in the content_script.js file, by using the line: `this.spacer = document.querySelector(".w-full.h-32.md\\:h-48.flex-shrink-0");` instead of `this.spacer = ...` in the init() method and inserting this line again in the methode fixLocation().

**Comment by spidy0x0** [comment]
> I had the same error (chrome 110.0.5481.104, chatGPT feb13 https://help.openai.com/en/articles/6825453-chatgpt-release-notes)
> 
> I ~ "fixed" it (I'm not familiar with JavaScript or browser plugin development) in the content_script.js file, by using the line: `this.spacer = document.querySelector(".w-full.h-32.md\\:h-48.flex-shrink-0");` instead of `this.spacer = ...` in the init() method and inserting this line again in the methode fixLocation().

this fixes it. now we need to make it adjust itself dynamically to minor changes

**Comment by tradeshark** [comment]
> I had the same error (chrome 110.0.5481.104, chatGPT feb13 https://help.openai.com/en/articles/6825453-chatgpt-release-notes)
> 
> I ~ "fixed" it (I'm not familiar with JavaScript or browser plugin development) in the content_script.js file, by using the line: `this.spacer = document.querySelector(".w-full.h-32.md\\:h-48.flex-shrink-0");` instead of `this.spacer = ...` in the init() method and inserting this line again in the methode fixLocation().

thx， it works
